services:
  firebase-emulators:
    build:
      context: .
      dockerfile: Dockerfile.emulators
    ports:
      - "4000:4000" # Emulator UI
      - "5001:5001" # Functions
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
    volumes:
      - ./functions:/workspace/functions
      - ./firebase.json:/workspace/firebase.json
      - ./firestore.rules:/workspace/firestore.rules
      - ./firestore.indexes.json:/workspace/firestore.indexes.json
      - ./.firebaserc:/workspace/.firebaserc
    working_dir: /workspace
    command: firebase emulators:start --import=./.emulator-data --export-on-exit
